#!/usr/bin/env bash
#Script transfer a file to your server that accepts 4 parameters

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 
else 

# Transfer the file using scp
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
