#!/usr/bin/env bash


if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else

path_to_file=$1
ip=$2
username=$3
ssh_key=$4

# Transfer the file using scp
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
