#!/usr/bin/env bash
#this  shebang tells the system to use the Bash shell to execute the script.

# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx
sudo ufw allow 80


# Create a default HTML file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

#testing nginx configurations
sudo service nginx start

# Restart Nginx
sudo /etc/init.d/nginx restart
