#!/usr/bin/env bash
# Script that installs nginx in an ubuntu terminal & Nginx listens to port 80
# returns Hello World when querying Nginx at its root using curl localhost
# /redirect_me should redirect to another page
# redirection must be 301 Moved Permanently

new_redirect="\tlocation /redirect_me {\n\t\t return 301 https://linkedin.com/in/christiana aghara;\n\t}\n"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "33s|.*|$new_redirect|" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
