#!/usr/bin/env bash
# Script that installs nginx in an ubuntu terminal & Nginx listens to port 80
# returns Hello World when querying Nginx at its root using curl localhost
# /redirect_me should redirect to another page
# redirection must be 301 Moved Permanently

# Upadating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/linkedin.com\/christiana aghara permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart
