#!/usr/bin/env bash
#Script that installs Nginx, Update package lists, creates default HTML file
#the shebang tells the system to use the Bash shell to execute the script.
#nginx will listen on port 80
# when querying Nginx at its root using curl localhost
# it should return "Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx restart
