#!/usr/bin/env bash
#This BashScript Creates a file containing its PID
#Displays TO infinity and beyond indefinitely
# Displays I hate the kill command when rceiving a SIGTERM signal
# Displays Y U no love me?! when recieving a SIGINT signal
#Deletes the file and terminates itself when recieving SIGQUIT signal


echo $$ > /var/run/myscript.pid

function sigterm_handler {
	trap echo "I hate the kill command"
	rm -rf /var/run/myscript.pid;
	exit 0
}
function sigint_handler {
	echo "Y U no love me?!"
}
function sigquit_handler {
	rm -rf /var/run/myscript.pid;
	exit 0
}

	echo "To infinity and beyond!"
 while true; do
 	sleep 2

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

done
