#!/usr/bin/env bash
#This Bash Script displays the content of the file /etc/passwd, using the while loop + IFS

filename=/etc/passwd

while IFS=: read -r username password uid gid full_name home shell
do


	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $full_name"

done < $filename
