#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on

"""ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-. can be done this way using ifconfig.ip command is preferable because some ifconfig can be missing in some os.""" 

ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
